# Copyright Laserfiche.
# Licensed under the MIT License. See LICENSE in the project root for license information.
name: build-test-publish

on:on:
  push:
    branches:
      - alex/update-pipelines
  pull_request:
    branches:
      - alex/update-pipelines
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_VERSION: '1.1.12'
  GITHUB_PAGES_BRANCH: 'gh-pages'

jobs:
  build_client_core:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: PNPM install
        run: pnpm install

      - name: PNPM run build
        run: pnpm run build --filter @laserfiche/lf-api-client-core

      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Copy license
        run: cp ./LICENSE ./packages/lf-api-client-core-js/LICENSE

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-client-core-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./packages/lf-api-client-core-js/dist
            ./packages/lf-api-client-core-js/package.json
            ./packages/lf-api-client-core-js/README.md
            ./packages/lf-api-client-core-js/LICENSE

  test_client_core:
    runs-on: ubuntu-latest
    needs: [ build_client_core ]
    steps:
      - uses: actions/checkout@v4

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: PNPM install
        run: pnpm install

      - name: Npm test on cloud
        id: test-cloud
        env:
          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
          ACCESS_KEY_JSON: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY_JSON }}
          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
        run: pnpm --filter @laserfiche/lf-api-client-core run test:Cloud

      - name: Npm test on self-hosted
        if: always() && (steps.test-cloud.outcome == 'success' || steps.test-cloud.outcome == 'failure')
        env:
          REPOSITORY_ID: ${{ secrets.APISERVER_REPOSITORY_ID }}
          APISERVER_USERNAME:  ${{ secrets.APISERVER_USERNAME }}
          APISERVER_PASSWORD:  ${{ secrets.APISERVER_PASSWORD }}
          APISERVER_REPOSITORY_API_BASE_URL:  ${{ secrets.APISERVER_REPOSITORY_API_BASE_URL }}
        run: pnpm --filter @laserfiche/lf-api-client-core run test:SelfHosted

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Jest Test Results
          path: ./packages/lf-api-client-core-js/*.xml
          reporter: jest-junit
          only-summary: "false"
          list-tests: "failed"
          fail-on-error: "false"

  build_api_client_v2:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install pnpm -g

      - name: PNPM install
        run: pnpm install

      - name: PNPM run build
        run: pnpm run build --filter @laserfiche/lf-repository-api-client-v2

      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Copy license
        run: cp ./LICENSE ./packages/lf-repository-api-client-v2/LICENSE

      - name: Upload a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-api-client-v2-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./packages/lf-repository-api-client-v2/dist
            ./packages/lf-repository-api-client-v2/package.json
            ./packages/lf-repository-api-client-v2/README.md
            ./packages/lf-repository-api-client-v2/LICENSE

  test_api_client_v2:
    runs-on: ubuntu-latest
    needs: [build_api_client_v2]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install pnpm -g

      - name: PNPM install
        run: pnpm install

# TODO remove unnecessary secrets
      - name: NPM test on cloud (node environment)
        id: test-cloud-node
        env:
          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
          REPOSITORY_ID: ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_1 }}
          AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
          TEST_HEADER: ${{ secrets.TEST_HEADER }}
        run: pnpm --filter @laserfiche/lf-repository-api-client-v2 run test:node

      - name: NPM test on cloud (browser environment)
        id: test-cloud-browser
        env:
          ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
          SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
          REPOSITORY_ID: ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_3 }}
          AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
          TEST_HEADER: ${{ secrets.TEST_HEADER }}
        run: pnpm --filter @laserfiche/lf-repository-api-client-v2 run test:browser

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Jest Test Results
          path: ./packages/lf-repository-api-client-v2/*.xml
          reporter: jest-junit
          only-summary: 'false'
          list-tests: 'failed'
          fail-on-error: 'false'


  publish-client-core-preview-package:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.run_attempt != 1 }}
    needs: [ build_client_core, test_client_core, build_api_client_v2, test_api_client_v2 ]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-client-core-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: set NpmPackageVersion as preview version from downloaded artifact
        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: pnpm version
        run: pnpm version ${{ env.NpmPackageVersion }} --no-git-tag-version

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: pnpm publish
        run: pnpm publish --filter @laserfiche/lf-api-client-core --access public  --tag next --no-git-checks

      - uses: actions/checkout@v4

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: lf-api-client-core-${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}


  publish-client-core-production-package:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.run_attempt != 1 }}
    needs: [ build_client_core, test_client_core, build_api_client_v2, test_api_client_v2, publish-client-core-preview-package ]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-client-core-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: pnpm version
        run: pnpm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: pnpm publish
        run: pnpm publish --filter @laserfiche/lf-api-client-core --access public  --tag next --no-git-checks

      - uses: actions/checkout@v4

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: lf-api-client-core-${{ env.NPM_VERSION }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}


  publish-api-client-v2-preview-package:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.run_attempt != 1 }}
    needs: [ build_client_core, test_client_core, build_api_client_v2, test_api_client_v2 ]
    steps:    
      - uses: actions/checkout@v4

      - name: Download a build artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-api-client-v2-publish-artifact
          path: ./packages/lf-repository-api-client-v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install pnpm -g

      - name: PNPM install
        run: pnpm install

      - name: Set NpmPackageVersion as preview version from downloaded artifact
        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: PNPM version
        working-directory: ./packages/lf-repository-api-client-v2
        run: pnpm version ${{ env.NpmPackageVersion }} --no-git-tag-version

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: PNPM publish
        working-directory: ./packages/lf-repository-api-client-v2
        run: pnpm publish --access public  --tag next --no-git-checks

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: lf-repository-api-client-v2-${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}

  publish-api-client-v2-production-package:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.run_attempt != 1 }}
    needs: [ build_client_core, test_client_core, build_api_client_v2, test_api_client_v2, publish-api-client-v2-preview-package ]
    steps:    
      - uses: actions/checkout@v4

      - name: Download a build artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-publish-api-client-v2-artifact
          path: ./packages/lf-repository-api-client-v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        run: npm install pnpm -g

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: PNPM version
        run: pnpm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version

      - name: PNPM publish
        working-directory: ./packages/lf-repository-api-client-v2
        run: pnpm publish  --access public  --tag latest

      - uses: actions/checkout@v4

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: lf-repository-api-client-v2-${{ env.NPM_VERSION }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}

# build and test client core
# build and test api client
# build documentation

# publish preview client core
   # publish production client core

# publish preview api client
   # publish production api client

# publish documentation