# Copyright Laserfiche.
# Licensed under the MIT License. See LICENSE in the project root for license information.

name: veracode-scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install dependencies
        run: pnpm install

      - name: Build solution
        run: pnpm run build

      - name: 'Create an empty ./veracode folder'
        run: 'mkdir -p ./veracode'

      - name: 'Compress js repository client v2 files'
        run: tar -czvf ./veracode/lf-repository-api-v2.tar.gz ./packages/lf-repository-api-client-v2/dist

      - name: 'Compress js api client core files'
        run: tar -czvf ./veracode/lf-client-core.tar.gz ./packages/lf-api-client-core-js/dist

      - name: 'Compress js repository client v1 files'
        run: tar -czvf ./veracode/lf-repository-api-v1.tar.gz ./packages/lf-repository-api-client-v1/dist

      - name: Veracode Upload And Scan (Static Application Security Testing)
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'lf-api-js'
          createprofile: true
          filepath: 'veracode'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          teams: 'GitHub - Open Source'

      - name: Run Veracode Software Composition Analysis (SCA)
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl --silent --show-error --location https://download.sourceclear.com/ci.sh | sh -s -- scan ./ --update-advisor --allow-dirty --recursive
